import './components/hero-slider'
import './components/theme'
import './components/awards-slider'
import './components/related-slider'
import './components/scroll'
import './components/project-gallery'